import { expect } from "chai";
import "reflect-metadata";
import { Connection } from "../../../../src";
import {
    closeTestingConnections,
    createTestingConnections,
    reloadTestingDatabases,
    sleep
} from "../../../utils/test-utils";
import { Post } from "./entity/Post";

describe("column kinds > version column", () => {

    let connections: Connection[];
    before(async () => connections = await createTestingConnections({
        entities: [__dirname + "/entity/*{.js,.ts}"],
    }));
    beforeEach(() => reloadTestingDatabases(connections));
    after(() => closeTestingConnections(connections));

    it("version column should automatically be set by a database", () => Promise.all(connections.map(async connection => {
        const postRepository = connection.getRepository(Post);

        const qr = connection.createQueryRunner();
        // save a new post
        const post = new Post();
        post.title = "Post";
        await postRepository.save(qr, post);

        // load and check if version is a date (generated by db)
        const loadedPost = await postRepository.findOne(qr);
        expect(loadedPost).to.be.not.empty;
        expect(loadedPost!.title).to.be.eql("Post");
        expect(loadedPost!.version).to.be.eql(1);

        await qr.release();
    })));

    it("version column should not update version if no changes were detected", () => Promise.all(connections.map(async connection => {
        const postRepository = connection.getRepository(Post);

        const qr = connection.createQueryRunner();
        // save a new post
        const post = new Post();
        post.title = "Post";
        await postRepository.save(qr, post);

        // update post once again
        const loadedPost1 = await postRepository.findOneOrFail(qr);
        await postRepository.save(qr, loadedPost1);

        // load and check if version was a value set by us
        const loadedPost2 = await postRepository.findOne(qr);

        // make sure version is the same
        expect(loadedPost2!.title).to.be.eql("Post");
        expect(loadedPost2!.version).to.be.eql(1);

        await qr.release();
    })));

    it("version column can also be manually set by user", () => Promise.all(connections.map(async connection => {
        const postRepository = connection.getRepository(Post);

        const qr = connection.createQueryRunner();
        // save a new post
        const post = new Post();
        post.title = "Post";
        post.version = 5;
        await postRepository.save(qr, post);

        // load and check if version was a value set by us
        const loadedPost = await postRepository.findOne(qr);
        expect(loadedPost).to.be.not.empty;
        expect(loadedPost!.title).to.be.eql("Post");
        expect(loadedPost!.version).to.be.eql(5);

        await qr.release();
    })));

    it("version column should be updated automatically on every change", () => Promise.all(connections.map(async connection => {
        const postRepository = connection.getRepository(Post);

        const qr = connection.createQueryRunner();
        // save a new post
        const post = new Post();
        post.title = "Post";
        await postRepository.save(qr, post);

        // wait a second
        await sleep(1000);

        // update post once again
        post.title = "Updated Title";
        await postRepository.save(qr, post);

        // check if date was updated
        const loadedPostAfterUpdate = await postRepository.findOne(qr);
        expect(loadedPostAfterUpdate!.version).to.be.eql(2);

        await qr.release();
    })));

    it("version column should set a custom value when specified", () => Promise.all(connections.map(async connection => {
        const postRepository = connection.getRepository(Post);

        const qr = connection.createQueryRunner();
        // save a new post
        const post = new Post();
        post.title = "Post";
        await postRepository.save(qr, post);

        // update post once again
        post.title = "Updated Title";
        post.version = 6;
        await postRepository.save(qr, post);

        // check if date was updated
        const loadedPost = await postRepository.findOne(qr);
        expect(loadedPost!.version).to.be.eql(6);

        await qr.release();
    })));
});
